### ISSUE TITLE
secondary_engine_range sensor not available in this repo

### ISSUE THREAD

**Issue by DutchKillerbee** [arjenvrh/audi_connect_ha#266]
I found one minor issue:
Using the repo of @t0bias-r the **secondary_engine_range** sensor exists and is properly filled: 

![image](https://github.com/arjenvrh/audi_connect_ha/assets/3790491/df8580be-6c9e-4772-9ea6-ff48e6fd7921)
In this repo the **secondary_engine_range** sensor doesn't exists:
![image](https://github.com/arjenvrh/audi_connect_ha/assets/3790491/833cdb44-6410-4203-8e88-e4a4c3460f98)

Thanks again

**Comment by Ingrimmsch93** [comment]
Thank you ;)
Can you provide your car data? 
easiest way to get it is, if you activate and deactivate debug log. This will automatically download a file. 
Important is only everything in this line:
<img width="764" alt="image" src="https://github.com/arjenvrh/audi_connect_ha/assets/16779969/4ac1b020-f6f7-4502-bb0c-06db15bc480a">

**Comment by DutchKillerbee** [comment]
@Ingrimmsch93 
her you are:
2024-03-07 21:09:20.165 DEBUG (MainThread) [custom_components.audiconnect.audi_services] audiconnect - Car Data: {'access': {'accessStatus': {'value': {'overallStatus': 'safe', 'carCapturedTimestamp': datetime.datetime(2024, 3, 7, 19, 7, 52, tzinfo=datetime.timezone.utc), 'doors': [{'name': 'bonnet', 'status': ['closed']}, {'name': 'frontLeft', 'status': ['locked', 'closed']}, {'name': 'frontRight', 'status': ['locked', 'closed']}, {'name': 'rearLeft', 'status': ['locked', 'closed']}, {'name': 'rearRight', 'status': ['locked', 'closed']}, {'name': 'trunk', 'status': ['locked', 'closed']}], 'windows': [{'name': 'frontLeft', 'status': ['closed']}, {'name': 'frontRight', 'status': ['closed']}, {'name': 'rearLeft', 'status': ['closed']}, {'name': 'rearRight', 'status': ['closed']}, {'name': 'roofCover', 'status': ['unsupported']}, {'name': 'sunRoof', 'status': ['closed']}], 'doorLockStatus': 'locked'}}}, 'charging': {'batteryStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 7, 20, 4, 58, tzinfo=datetime.timezone.utc), 'currentSOC_pct': 85, 'cruisingRangeElectric_km': 33}}, 'chargingStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 7, 20, 4, 58, tzinfo=datetime.timezone.utc), 'remainingChargingTimeToComplete_min': 50, 'chargingState': 'charging', 'chargeMode': 'manual', 'chargeType': 'unsupported'}}, 'plugStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 7, 20, 4, 58, tzinfo=datetime.timezone.utc), 'plugConnectionState': 'connected', 'plugLockState': 'locked', 'externalPower': 'ready', 'ledColor': 'green'}}, 'chargeMode': {'value': {'preferredChargeMode': 'manual', 'availableChargeModes': ['manual', 'timer']}}}, 'chargingTimers': {'chargingTimersStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 2, 29, 21, 25, 4, tzinfo=datetime.timezone.utc), 'timeInCar': '', 'timers': [{'id': 1, 'enabled': False, 'climatisation': False, 'preferredChargingTimes': [{'id': 1, 'enabled': True, 'startTimeLocal': '09:00', 'endTimeLocal': '16:00'}], 'recurringTimer': {'departureTimeLocal': '12:00', 'targetTimeLocal': '12:00', 'repetitionDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'], 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}}}, {'id': 2, 'enabled': False, 'climatisation': False, 'preferredChargingTimes': [{'id': 1, 'enabled': True, 'startTimeLocal': '09:00', 'endTimeLocal': '16:00'}], 'singleTimer': {'targetDateTimeLocal': '2024-03-08T08:00:00', 'departureDateTimeLocal': '2024-03-08T08:00:00'}}]}}}, 'climatisationTimers': {'climatisationTimersStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 2, 29, 21, 25, 4, tzinfo=datetime.timezone.utc), 'timers': [{'id': 1, 'enabled': False, 'singleTimer': {'startDateTimeLocal': '2024-01-19T07:55:00', 'targetDateTimeLocal': '2024-01-19T07:55:00'}}]}}}, 'fuelStatus': {'rangeStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 7, 20, 4, 58, tzinfo=datetime.timezone.utc), 'carType': 'hybrid', 'primaryEngine': {'type': 'gasoline', 'currentSOC_pct': 52, 'remainingRange_km': 350, 'currentFuelLevel_pct': 52}, 'secondaryEngine': {'type': 'electric', 'currentSOC_pct': 85, 'remainingRange_km': 33}, 'totalRange_km': 383}}}, 'measurements': {'rangeStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 7, 20, 4, 58, tzinfo=datetime.timezone.utc), 'electricRange': 33, 'gasolineRange': 350, 'totalRange_km': 383}}, 'odometerStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 7, 19, 7, 52, tzinfo=datetime.timezone.utc), 'odometer': 99414}}, 'fuelLevelStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 7, 20, 4, 58, tzinfo=datetime.timezone.utc), 'currentFuelLevel_pct': 52, 'currentSOC_pct': 85, 'primaryEngineType': 'gasoline', 'secondaryEngineType': 'electric', 'carType': 'hybrid'}}}, 'vehicleLights': {'lightsStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 7, 19, 7, 52, tzinfo=datetime.timezone.utc), 'lights': [{'name': 'right', 'status': 'off'}, {'name': 'left', 'status': 'off'}]}}}, 'vehicleHealthInspection': {'maintenanceStatus': {'value': {'carCapturedTimestamp': datetime.datetime(2024, 3, 7, 19, 7, 49, tzinfo=datetime.timezone.utc), 'inspectionDue_days': 555, 'inspectionDue_km': 10000, 'mileage_km': 99414, 'oilServiceDue_days': 329, 'oilServiceDue_km': 11400}}}}

**Comment by t0bias-r** [comment]
It could be the comma `"remainingRange_km",`:
https://github.com/arjenvrh/audi_connect_ha/blob/f4bf37562a71332b06accdd745f05579862b681a/custom_components/audiconnect/audi_models.py#L160C1-L160C37

**Comment by Ingrimmsch93** [comment]
Yes could be. I think its strange, because we both have very similar car data (this part is identical) and it is working for me, but not for him.
Lets try it. I will remove the comma (also from the others) and create a PR.

**Comment by DutchKillerbee** [comment]
I tried to change the file locally and noticed that I had a complete other audi_models.py file ?!?
I re-downloaded the integration and now the sensor is there
![image](https://github.com/arjenvrh/audi_connect_ha/assets/3790491/17e5b6d9-4dc5-4767-901d-09bc8df5d1c7)

PS the extra , is still there so it works with the extra ,
![image](https://github.com/arjenvrh/audi_connect_ha/assets/3790491/f094fe2c-5e72-4835-a820-1107dd8fda08)

**Comment by Ingrimmsch93** [comment]
strange... okay nevermind i created a PR to remove the comma.
Please close this issue, if solved :)

**Comment by DutchKillerbee** [comment]
Done

**Comment by guidokieboom** [comment]
@DutchKillerbee @Ingrimmsch93 For me this still doesn't work. I've installed the latest version (77e36ba). 
<img width="323" alt="image" src="https://github.com/arjenvrh/audi_connect_ha/assets/65387179/147da73f-f0d6-4a17-9407-cf029c4d3d9e">
My entities list shown no sensor about secondary engine range.
<img width="975" alt="image" src="https://github.com/arjenvrh/audi_connect_ha/assets/65387179/401c1826-584c-4a63-a6c4-01a1ef46d101">
Maybe following helps to troubleshoot:
<img width="541" alt="image" src="https://github.com/arjenvrh/audi_connect_ha/assets/65387179/43b7cdcd-ab0f-49a8-8ecd-841e1016d237">

**Comment by Ingrimmsch93** [comment]
@guidokieboom can you provide your car data, please?
So i can double check, if HA is receiving the information like expected.

**Comment by guidokieboom** [comment]
sure. Car is Audi A6 Avant tfsi e (2023). If you like more information, can you advise how I can find that?

**Comment by Ingrimmsch93** [comment]
yes i described it in aboves comment: https://github.com/arjenvrh/audi_connect_ha/issues/266#issuecomment-1984326692

As this original issue is different and solved, can you please create a new issue?
It helps us keep a better overview :)
